export var buzzwords = [
  '4g',
  '5g',
  'accountable talk',
  'agile',
  'ajax',
  'algorithm',
  'alignment',
  'ambiguity',
  'amplify',
  'analytics',
  'andon',
  'api',
  'artisan',
  'at the end of the day',
  'back-end',
  'ballpark figure',
  'bandwidth',
  'benchmarking',
  'best of breed',
  'best practices',
  'beta',
  'big data',
  'big society',
  'bio-',
  'bizmeth',
  'bleeding edge',
  'blockchain',
  "bloom's taxonomy",
  'break through the clutter',
  'brick-and-mortar',
  'bricks-and-clicks',
  'bring to the table',
  'bring your own device',
  'building capabilities',
  'business process outsourcing',
  'business-to-business',
  'business-to-consumer',
  'buzzword',
  'buzzword compliant',
  'cadence',
  'catchphrase',
  'clear goal',
  'clickthrough',
  'client-centric',
  'close the loop',
  'cloud-computing',
  'co-opetition',
  'collaboration',
  'come-to-jesus moment',
  'common core',
  'content management',
  'content management system',
  'content marketing',
  'convergence',
  'core competency',
  'corporate jargon',
  'coward',
  'creative',
  'cross-platform',
  'css3',
  'customer-centric',
  'cyber-physical systems',
  'data mining',
  'data science',
  'datafication',
  'deep dive',
  'deep learning',
  'deep web',
  'design pattern',
  'devops',
  'differentiated instruction',
  'digital divide',
  'digital literacy',
  'digital remastering',
  'digital rights management',
  'digital signage',
  'disruptive innovation',
  'disruptive technologies',
  'diversity',
  'document management',
  'dot-bomb',
  'downsizing',
  'drill down',
  'drinking the kool-aid',
  'e-learning',
  'early-stage',
  'eating your own dogfood',
  'eco-',
  'emotional intelligence',
  'employer branding',
  'empowerment',
  'enable',
  'end-to-end',
  'engine',
  'enterprise content management',
  'enterprise service bus',
  'entitlement',
  'ephemeral rogue entity',
  'establishment',
  'evangelist',
  'event horizon',
  'exit strategy',
  'eyeballs',
  'face time',
  'fit for purpose',
  'fleet dynamism',
  'flipped classroom',
  'folksonomy',
  'framework',
  'free value',
  'frictionless',
  'front-end',
  'fulfilment issues',
  'fuzzy logic',
  'generation x',
  'generation y',
  'globalization',
  'going forward',
  'grow',
  'growth hacking',
  'guided reading',
  'headlights',
  'heavy lifting',
  'herding cats',
  'higher-order thinking',
  'holistic',
  'holistic approach',
  'home',
  'html5',
  'hype cycle',
  'hyperlocal',
  'iaas',
  'ideation management',
  'immersion',
  'impact',
  'information society',
  'information superhighway',
  'innovation',
  'innovative',
  'instructional scaffolding',
  'internet of things',
  'invested in',
  'javascript',
  'knowledge process outsourcing',
  'lambda',
  'lateral violence',
  'law of the instrument',
  'leverage',
  'list of buzzwords',
  'logistics',
  'long tail',
  'low hanging fruit',
  'machine learning',
  'make it pop',
  'management visibility',
  'marketing buzz',
  'mashup',
  'memetics',
  'microservices',
  'millennial',
  'mind share',
  'mindshare',
  'mission critical',
  'mobile',
  'modularity',
  'mouthfeel',
  'moving forward',
  'multiple intelligences',
  'nanotechnology',
  'national security',
  'netiquette',
  'new economy',
  'new normal',
  'next generation',
  'offshoring',
  'on the runway',
  'one team',
  'open source',
  'opportunities',
  'optics',
  'organic growth',
  'paas',
  'pain point',
  'paradigm',
  'paradigm shift',
  'paralysis by analysis',
  'passionate',
  'pleonasm',
  'podcasting',
  'political capital',
  'power word',
  'privacy',
  'proactive',
  'productivity',
  'profit center',
  'project-based learning',
  'psychobabble',
  'push the envelope',
  'quantum supremacy',
  'quick win',
  'reach out',
  'real-time',
  'reimagine',
  'resonate',
  'responsive web design',
  'return on investment',
  'reverse fulfilment',
  'rightshoring',
  'roadmap',
  'robust',
  'run like a business',
  'rustic',
  'saas',
  'scalability',
  'sea change',
  'seamless',
  'sensorization',
  'serum',
  'share options',
  'single pane-of-glass',
  'sisterhood',
  'skeuomorphic',
  'social bookmarking',
  'social software',
  'software defined networking',
  'solidarity',
  'solution',
  'sox',
  'spa',
  'spam',
  'spin-up',
  'stack',
  'stakeholder',
  'startup',
  'storytelling',
  'strategic communication',
  'strategic ineptness',
  'streamline',
  'student engagement',
  'survival strategy',
  'sustainability',
  'sync-up',
  'synergy',
  'systems development life-cycle',
  'tagging',
  'take offline',
  'talent relationship management',
  'think outside the box',
  'tiger team',
  'time-blindness',
  'toolchain',
  'touchpoint',
  'transmedia',
  'unpack',
  'user generated content',
  'value add',
  'value-added',
  'viral',
  'virtualization',
  'virtue word',
  'visibility',
  'vortal',
  'warfighter',
  'water under the bridge',
  'weasel word',
  'web 2.0',
  'web services',
  'webinar',
  'wellness',
  'wheelhouse',
  'wikiality',
  'win-win',
  'work smarter',
  'workflow'
]
