export const buzzwords = [
  '4g',
  '5g',
  'accountable talk',
  'adaptive interface',
  'agile',
  'ajax',
  'algorithm',
  'alignment',
  'ambient environment',
  'ambiguity',
  'amplify',
  'analysis paralysis',
  'analytics',
  'andon',
  'antifragile',
  'api',
  'artisan',
  'at the end of the day',
  'augmented reality',
  'back-end',
  'ballpark figure',
  'bandwidth',
  'benchmarking',
  'best practices',
  'best-of-breed',
  'beta',
  'big data',
  'big society',
  'bio-',
  'bizmeth',
  'bleeding edge',
  'blockchain',
  'blockchain network',
  "bloom's taxonomy",
  'break through the clutter',
  'brick-and-mortar',
  'bricks-and-clicks',
  'bring to the table',
  'bring your own device',
  'building capabilities',
  'business process outsourcing',
  'business-to-business',
  'business-to-consumer',
  'buzzword',
  'buzzword compliant',
  'cadence',
  'catchphrase',
  'clear goal',
  'clickthrough',
  'cloud-computing',
  'co-opetition',
  'collaboration',
  'come-to-jesus moment',
  'common core',
  'content management',
  'content management system',
  'content marketing',
  'convergence',
  'core competency',
  'corporate jargon',
  'coward',
  'creative',
  'critical thinking',
  'cross-platform',
  'css3',
  'customer-centric',
  'cutting edge',
  'cyber-physical systems',
  'data mining',
  'data science',
  'datafication',
  'decentralized',
  'deep dive',
  'deep learning',
  'deep web',
  'design pattern',
  'devops',
  'differentiated instruction',
  'digital divide',
  'digital literacy',
  'digital remastering',
  'digital rights management',
  'digital signage',
  'disruptive innovation',
  'disruptive technologies',
  'diversity',
  'document management',
  'dot-bomb',
  'downsizing',
  'drill down',
  'drinking the kool-aid',
  'e-learning',
  'early-stage',
  'eating your own dogfood',
  'eco-',
  'emotional intelligence',
  'employer branding',
  'empowerment',
  'enable',
  'end-to-end',
  'engine',
  'enterprise content management',
  'enterprise service bus',
  'entitlement',
  'ephemeral rogue entity',
  'establishment',
  'evangelist',
  'event horizon',
  'exit strategy',
  'expanding the curriculum',
  'eyeballs',
  'face time',
  'falter-step',
  'fit for purpose',
  'fleet dynamism',
  'flipped classroom',
  'folksonomy',
  'framework',
  'free value',
  'frictionless',
  'front-end',
  'fulfilment issues',
  'future-proof',
  'futuristic progress',
  'fuzzy logic',
  'generation x',
  'generation y',
  'globalist business conglomerate',
  'globalization',
  'going forward',
  'grow',
  'growth hacking',
  'guided reading',
  'headlights',
  'heavy lifting',
  'herding cats',
  'higher-order thinking',
  'holistic',
  'holistic approach',
  'home',
  'hots',
  'html5',
  'hype cycle',
  'hyperlocal',
  'iaas',
  'ideation management',
  'immersion',
  'impact',
  'information society',
  'information superhighway',
  'innovation',
  'innovative',
  'instructional scaffolding',
  'intergalactic ai',
  'internet of things',
  'intuitive ai',
  'invested in',
  'javascript',
  'knowledge process outsourcing',
  'lambda',
  'lateral violence',
  'law of the instrument',
  'learned lexicon',
  'left-handed',
  'leverage',
  'logistical nightmare',
  'logistics',
  'long tail',
  'long-term goals',
  'low-hanging fruit',
  'machine learning',
  'make it pop',
  'management visibility',
  'marketing buzz',
  'mashup',
  'mass-marketable',
  'memetics',
  'metaverse',
  'microservices',
  'millennial',
  'mind share',
  'mindshare',
  'mission critical',
  'mobile',
  'modularity',
  'mouthfeel',
  'moving forward',
  'multimedia',
  'multiple intelligences',
  'nanodegree',
  'nanotechnology',
  'national security',
  'negligible profit loss',
  'netiquette',
  'network marketing',
  'neural expansion',
  'neurotechnology',
  'new economy',
  'new normal',
  'new-world innovation',
  'next generation',
  'offshoring',
  'on the ground research',
  'on the runway',
  'one and done',
  'one team',
  'open source',
  'opportunities',
  'optics',
  'organic growth',
  'paas',
  'pain point',
  'paradigm',
  'paradigm shift',
  'passionate',
  'pedagogy',
  'pleonasm',
  'podcasting',
  'political capital',
  'power word',
  'practicing businessman',
  'privacy',
  'proactive',
  'productivity',
  'profit center',
  'profit parallelogram',
  'project-based learning',
  'psychobabble',
  'push the envelope',
  'quadral thinking',
  'quantum',
  'quantum supremacy',
  'quick win',
  'reach out',
  'real-time',
  'red line',
  'reimagine',
  'research firm',
  'resonate',
  'responsive web design',
  'return on investment',
  'reverse fulfilment',
  'rightshoring',
  'roadmap',
  'robust',
  'run like a business',
  'rustic',
  'saas',
  'scalability',
  'sea change',
  'seamless',
  'sensorization',
  'serum',
  'share options',
  'showroom prototype',
  'side-hustle',
  'single pane-of-glass',
  'sisterhood',
  'skeuomorphic',
  'slow-growth factors',
  'smart marketing',
  'smart partnership',
  'social bookmarking',
  'social software',
  'software defined networking',
  'solidarity',
  'solution',
  'sox',
  'spa',
  'space race',
  'spam',
  'spatial awareness',
  'spin-up',
  'stack',
  'stakeholder',
  'startup',
  'step-ladder hierarchy',
  'storytelling',
  'strategic communication',
  'strategic ineptness',
  'streamline',
  'student engagement',
  'survival strategy',
  'sustainability',
  'sync-up',
  'synergy',
  'systems development life-cycle',
  'tagging',
  'take offline',
  'talent relationship management',
  'technically apt',
  'tenured professor',
  'terminal velocity',
  'thermal technology',
  'think outside the box',
  'tiger team',
  'time-blindness',
  'toolchain',
  'touchpoint',
  'transmedia',
  'unpack',
  'user generated content',
  'user-friendly',
  'value add',
  'value-added',
  'viral',
  'virtualization',
  'virtue word',
  'visibility',
  'vortal',
  'warfighter',
  'water under the bridge',
  'weasel word',
  'web 2.0',
  'web services',
  'webinar',
  'wellness',
  'wheelhouse',
  'wikiality',
  'win-win',
  'work smarter',
  'workflow'
]
